
ALTER TABLE schedule NOCHECK CONSTRAINT all;
ALTER TABLE uplink NOCHECK CONSTRAINT all;
ALTER TABLE feedFlag NOCHECK CONSTRAINT all;


ALTER TABLE PackageElement NOCHECK CONSTRAINT all;
ALTER TABLE Package_Flag NOCHECK CONSTRAINT all;
ALTER TABLE Package_Attribute NOCHECK CONSTRAINT all;
ALTER TABLE Package NOCHECK CONSTRAINT all;
ALTER TABLE ElementType NOCHECK CONSTRAINT all;
ALTER TABLE FlagType NOCHECK CONSTRAINT all;
ALTER TABLE FlagClass NOCHECK CONSTRAINT all;
ALTER TABLE Attribute NOCHECK CONSTRAINT all;
ALTER TABLE Disclaimer NOCHECK CONSTRAINT all;
ALTER TABLE Rating NOCHECK CONSTRAINT all;
ALTER TABLE PackageType NOCHECK CONSTRAINT all;



ALTER TABLE Asset_Rights NOCHECK CONSTRAINT all;
ALTER TABLE Reup_Funder NOCHECK CONSTRAINT all;
ALTER TABLE Reup_Contact NOCHECK CONSTRAINT all;
ALTER TABLE Reup NOCHECK CONSTRAINT all;
ALTER TABLE ProgramSegment_SegmentCategory NOCHECK CONSTRAINT all;
ALTER TABLE ProgramSegment NOCHECK CONSTRAINT all;
ALTER TABLE Asset_RelatedRights NOCHECK CONSTRAINT all;
ALTER TABLE Asset_Talent NOCHECK CONSTRAINT all;
ALTER TABLE Asset_Genre NOCHECK CONSTRAINT all;
ALTER TABLE Asset_Keyword NOCHECK CONSTRAINT all;
ALTER TABLE Asset_TiVoKeyword NOCHECK CONSTRAINT all;
ALTER TABLE Program_Format NOCHECK CONSTRAINT all;
ALTER TABLE Asset NOCHECK CONSTRAINT all;

ALTER TABLE SegmentCategory NOCHECK CONSTRAINT all;
ALTER TABLE Rights_Rule NOCHECK CONSTRAINT all;
ALTER TABLE channel NOCHECK CONSTRAINT all;
ALTER TABLE Rights_Group NOCHECK CONSTRAINT all;
ALTER TABLE company NOCHECK CONSTRAINT all;
ALTER TABLE contactType NOCHECK CONSTRAINT all;
ALTER TABLE TalentRole NOCHECK CONSTRAINT all;
ALTER TABLE Talent NOCHECK CONSTRAINT all;
ALTER TABLE genre NOCHECK CONSTRAINT all;
ALTER TABLE keyword NOCHECK CONSTRAINT all;
ALTER TABLE TiVoKeyword NOCHECK CONSTRAINT all;
ALTER TABLE format NOCHECK CONSTRAINT all;
ALTER TABLE Vchip NOCHECK CONSTRAINT all;
ALTER TABLE FeedDistributor NOCHECK CONSTRAINT all;
ALTER TABLE category NOCHECK CONSTRAINT all;
